### ISSUE TITLE
InitContainer fail

### ISSUE THREAD

**Issue by phal0r** [digitalist-se/matomo-kubernetes#14]
Hi guys,

thanks for this cool project. I wanted to give it a try, but it fails for me durinig initialization with the following errors in initContainer of all deployments:

```
The configuration file {/var/www/html/config/config.ini.php} has not been found or could not be read.
» Please check that /var/www/html/config/config.ini.php is readable by the user 'www-data'.
[Zend_Db_Adapter_Exception]
SQLSTATE[HY000] [2002] No such file or directory

[PDOException]
SQLSTATE[HY000] [2002] No such file or directory
plugin:activate [plugin1] ... [pluginN]
```

Seems like it is a problem with emptyDir. Any ideas?

**Comment by sasko-z** [comment]
Hi, try to add this values in the specs for init:

`securityContext:
            runAsUser: 33
            privileged: false
            allowPrivilegeEscalation: false`

**Comment by phal0r** [comment]
Thanks for the suggestion. It changes the user, but the error remains the same:
```
The configuration file {/var/www/html/config/config.ini.php} has not been found or could not be read.
--
Sat, Sep 10 2022 5:21:33 pm | » Please check that /var/www/html/config/config.ini.php is readable by the user 'xfs'.
```

**Comment by mikkeschiren** [comment]
That message will always be printed out - in a successful install also.

**Comment by phal0r** [comment]
@mikkeschiren Thanks for the clarification, but in my case the initContainer fail to start and this is the only thing, that is being logged, so I have no idea how to debug this.

**Comment by sasko-z** [comment]
Replace installCommand in values with following:

`sleep 6000 #sleep command so container will not exit, for debug`

After that check if owner and group of "/var/www/html/config/config.ini.php" is ID 33, if it's not then replace the ID with the correct one.

**Comment by mikkeschiren** [comment]
Hm, interesting, I never had that issue - what is the complete command you use with matomo:install @phal0r ?

**Comment by sasko-z** [comment]
> Hm, interesting, I never had that issue - what is the complete command you use with matomo:install @phal0r ?

I had similar issue before, it depends from the setup and which image you are using.

fpm-alpine has ID 82 for www-data:
`www-data:x:82:82:Linux User,,,:/home/www-data:/sbin/nologin`

apache has ID 33:
`www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin`

That's why `runAsUser` need to be defined with correct ID.

**Comment by mikkeschiren** [comment]
So maybe if you add an override for the user in your own values file for matomo:runAsUser, you will get it running

**Comment by phal0r** [comment]
Hi guys,

thanks for the insights. I will give it another try in the next days. I didn't modify much in the values.yaml apart from database and initial user credentials.

**Comment by mikkeschiren** [comment]
I hope to spend som time on the documentation and adding tests in the coming months. That should help people out using this chart.

**Comment by bayerlse** [comment]
Hey @phal0r ! Did you get it working? Having the same problem.

**Comment by bayerlse** [comment]
I fixed it by copying the common.config.ini.php and rename it to config.ini.php. I also adjusted the run command to be not required to exit with 0, after that, the initContainer ran successful.
