### ISSUE TITLE
Environment variables not read

### ISSUE THREAD

**Issue by roflmao** [digitalist-se/matomo-kubernetes#15]
Seems i have to setup config.inc.php to get the chart to talk to the database.
Is this due to the EnvironmentVariables plugin is not enabled by default?

I also see other references to MATOMO_$CATEGORY_$SETTING from https://plugins.matomo.org/EnvironmentVariables which then again should be MATOMO_DATABASE_HOST.
But the helm chart uses MATOMO_DB_HOST?

**Comment by mikkeschiren** [comment]
The chart is not dependent on the EnvironmentVariables plugin, it's dependent on the ExtraTools plugin, which uses the default variables for DB (like the official docker image).
