### ISSUE TITLE
outdated PHP version

### ISSUE THREAD

**Issue by Seeron** [digitalist-se/matomo-kubernetes#28]
The current image runs with PHP 8.0, which is EOL since the beginning of this year. Are there any plans to update the images to a newer version? Or could you provide a link to the current Dockerfile, then I could create a PR there

**Comment by mikkeschiren** [comment]
Hi, the image provided is more a dummy image, it works fine - but like you said - outdated, but we still don't have an automatic process to update it in the chart, I hope to get that in place real soon. But thank you for creating this issue and reminding me.

**Comment by mikkeschiren** [comment]
I have updated the image and bumbed the app version. So closing this.
