### ISSUE TITLE
is it required any customization to matomo image?

### ISSUE THREAD

**Issue by esedeka** [digitalist-se/matomo-kubernetes#8]
Hi,

I'm trying to deploy Matomo using your helm chart but I'm unable to make it run. I have MySQL and Redis up and running,  I have replaced matomo with custom built 3.14.1 image pulled from my registry and nginx with 1.16.1-alpine from docker hub.

Also I've built wait-for-200 and pulled from my registry.

matomo-init seems to fail with 

sh: rsync: not found 

installing rsync on matomo image seems to solve that problem but matomo-init stills failing. and pods still not going up and running.

Do I need to add something else to matomo image? If so, can you provide any advice? 

Thank you very much indeed!

**Comment by esedeka** [comment]
Hi,

I think I have managed to reproduce the suitable matomo docker image and I have all the pods running, now I just get the following error after login on matomo dahsboard with the created admin user:

Error: no website was found in this Matomo installation.
Check the table 'matomo_site' in your database, it should contain your Matomo websites.

Any clue?

Thank you very much indeed!

**Comment by jorgeuos** [comment]
Hi,

What are you running in your installCommand? I guess you could just add a site manually, just remember to use the `--do-not-drop-db` in the installCommand and that message should go away.

Br, Jorge
